export const SET_COUNTRY_LIST = 'SET_COUNTRY_LIST'
export const SET_COUNTRY_VIEW = 'SET_COUNTRY_VIEW'
export const SET_FAVOURITES = 'SET_FAVOURITES'
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES'
